module.exports = {
  // keys:
  LP_SOCKET: "LP_SOCKET_STATUS",
  BC_SOCKET: "BC_SOCKET_STATUS",
  NODE_STATUS: "NODE_STATUS",
  USER_TO_BOT: "USER_TO_BOT",
  BOT_TO_USER: "BOT_TO_USER",

  // messages:
  STARTED : "STARTED",
  STOPPED : "STOPPED",

  // message types:
  TYPE_QUICK_REPLY:  'TYPE_QUICK_REPLY',
  TYPE_GENERIC:  'TYPE_GENERIC',
  TYPE_BUTTON:  'TYPE_BUTTON',
  TYPE_CAROUSEL:  'TYPE_CAROUSEL',
  TYPE_LISTPICKER:  'TYPE_LISTPICKER',
  TYPE_IMAGE:  'TYPE_IMAGE',
  TYPE_VIDEO:  'TYPE_VIDEO',
  TYPE_AUDIO:  'TYPE_AUDIO',
  TYPE_TEXT : 'TYPE_TEXT',
  TYPE_UNKNOWN : 'TYPE_UNKNOWN'
}
